sudo: required
services:
  - docker

before_install:
  - docker build -t billiramirez/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run billiramirez/react-test npm run test -- --coverage

after_success:
  - docker build -t billiramirez/multi-client ./client
  - docker build -t billiramirez/multi-nginx ./nginx
  - docker build -t billiramirez/multi-server ./server
  - docker build -t billiramirez/multi-worker ./worker
  # Log in into docker  CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push it to docker hub
  - docker push billiramirez/multi-client
  - docker push billiramirez/multi-nginx
  - docker push billiramirez/multi-server
  - docker push billiramirez/multi-worker
